### ISSUE TITLE
Status bar covering views in the storyboard

### ISSUE THREAD

**Issue by Lee627** [ChapmanCPSC370/TLT_SIgn_in_app#9]
I noticed that the status bar covers the view area underneath the status bar. I believe this is a simple fix and I can take care of it as soon as possible.

**Comment by samyachour** [comment]
Sounds good

**Comment by samyachour** [comment]
On second thought that's the navigation bar which can't be moved so i'm gonna delete it and change some stuff. I can take care of this issue

**Comment by samyachour** [comment]
Done.
